name: Backend LisMusic CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: docker build -t reader-service ./deployment/reader-service .
    - name: Tags
      run: |
        docker tag reader-service ${{ secrets.DOCKER_USER }}/reader-service:${{ github.sha }}
        docker tag reader-service ${{ secrets.DOCKER_USER }}/reader-service:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_USER }}/reader-service:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/reader-service:latest
